package constant

const (
	ACCOUNT_STATUS_ACTIVE   = 1
	ACCOUNT_STATUS_INACTIVE = 2

	SECURITY_TYPE_STOCK        = 1
	SECURITY_TYPE_STOCK_STRING = "stock"

	EXCHANGE_TYPE_NSE = 1
	EXCHANGE_TYPE_BSE = 2

	EXCHANGE_TYPE_NSE_STRING = "NSE"
	EXCHANGE_TYPE_BSE_STRING = "BSE"
)
