package constant

const (
	ACCOUNT_STATUS_ACTIVE   = 1
	ACCOUNT_STATUS_INACTIVE = 2

	SECURITY_TYPE_STOCK              = 1
	SECURITY_TYPE_MUTUAL_FUND        = 2
	SECURITY_TYPE_STOCK_STRING       = "stock"
	SECURITY_TYPE_MUTUAL_FUND_STRING = "mutualFund"

	EXCHANGE_TYPE_NSE = 1
	EXCHANGE_TYPE_BSE = 2

	EXCHANGE_TYPE_NSE_STRING = "NSE"
	EXCHANGE_TYPE_BSE_STRING = "BSE"
)

const (
	ERROR_CODE_INTERNAL_SERVER = "SE01"

	ERROR_CODE_REQUEST_INVALID        = "RE01"
	ERROR_CODE_REQUEST_PARAMS_INVALID = "RE02"

	ERROR_CODE_NO_DATA = "DA01"
)
